github.com:
    users:
        harry-urek:
            oauth_token: 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
    git_protocol: ssh
    user: harry-urek
    oauth_token: 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
